language: java
env:
- TERM=dumb
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8
script:
- ./gradlew check --info
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
